freebsd_task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-2
  env:
    PATH: /usr/local/bin:$PATH
  prep_script:
    - dd if=/dev/zero of=/tmp/zpool bs=1M count=1024
    - zpool create -m `pwd`/testtmp zpool /tmp/zpool
    - pkg install -y bash autotools m4 xxhash zstd liblz4 wget
    - wget -O git-version.h https://gist.githubusercontent.com/WayneD/c11243fa374fc64d4e42f2855c8e3827/raw/rsync-git-version.h
  configure_script:
    - CPPFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib/ ./configure --disable-md2man
  make_script:
    - make
  install_script:
    - make install
  info_script:
    - rsync --version
  test_script:
    - RSYNC_EXPECT_SKIPPED=acls-default,acls,crtimes,protected-regular make check
  ssl_file_list_script:
    - rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
