#! /bin/sh

# Actually, rsync tests do too exist.  They're in this strangely-named
# directory to support old installations of the build farm client
# software.

echo "$0 running" 

TEST_ALL="rsync-hello"
