#!/bin/sh

# You can put this script early on your PATH to support a top-dir "make"
# changing into a per-branch build dir before running the make.  Just start
# with a pristine top dir (e.g. run "make distclean") and then create the dir
# "build/master", at which point you can stay in the top dir of the source and
# run "./configure" and "make" commands and have the appropriate build dir be
# automatically used (the non-master subdirs will be auto-created).

if [ ! -f Makefile -a -d build/master -a -d .git -a x"$1" != x-* ]; then
    builddir=build/`git rev-parse --abbrev-ref HEAD | tr / %`
    [ -d "$builddir" ] || mkdir "$builddir"
    # Let make do a noisy chdir so that a calling editor knows where the files are.
    set -- -C "$builddir" ${1+"$@"}
fi

export PATH="/usr/lib/ccache:$PATH"
exec /usr/bin/make ${1+"$@"}
