#!/bin/bash -e

cat >/dev/null # Just discard stdin data

if [[ -f /proc/$PPID/cmdline ]]; then
    while read -d $'\0' arg ; do
	if [[ "$arg" == '--tags' ]] ; then
	    exit 0
	fi
    done </proc/$PPID/cmdline
fi

branch=`git rev-parse --abbrev-ref HEAD`
if [[ "$branch" = master && "$*" == *github* ]]; then
    make gensend
fi
