#!/bin/sh
 
set -e

export LANG=C

make=`which gmake 2>/dev/null` || make=`which make 2>/dev/null`

branch=`packaging/prep-auto-dir`
if test x"$branch" = x; then
    srcdir=.
else
    cd build
    srcdir=..
fi

if test -f configure.sh; then
    cp -p configure.sh configure.sh.old
else
    touch configure.sh.old
fi

if test -f .fetch; then
    $srcdir/prepare-source fetch
else
    $srcdir/prepare-source
fi

if diff configure.sh configure.sh.old >/dev/null 2>&1; then
    echo "configure.sh is unchanged."
    rm configure.sh.old
else
    echo "configure.sh has CHANGED."
    if test -f config.status; then
	./config.status --recheck
    else
	$srcdir/configure
    fi
fi

./config.status

$make all

if test x"$1" = x"check"; then
    $make check
fi
