#!/usr/bin/env python3
"""Portable replacements for rsync's *.awk header generators.

The stock build shells out to awk to produce proto.h, daemon-parm.h,
help-*.h and default-*.h.  Windows has no awk, so CMake drives this
script instead.  Each sub-command mirrors the corresponding .awk file
closely enough to produce byte-identical output.

Copyright (C) 2026 Max Vilimpoc, rsync CMake/Windows port.
Distributed under the same GPL-3.0-or-later terms as the rest of rsync.
"""

import argparse
import os
import re
import sys


def _write_if_changed(path, text):
    """Match awk's habit of leaving the file alone when nothing changed."""
    try:
        with open(path, "r", newline="") as fh:
            if fh.read() == text:
                return
    except OSError:
        pass
    with open(path, "w", newline="") as fh:
        fh.write(text)


# --------------------------------------------------------------------------
# mkproto.awk
# --------------------------------------------------------------------------

FN_RE = re.compile(r"^FN_(LOCAL|GLOBAL)_[^(]+\([^,()]+")
SKIP_RE = re.compile(r"^static|^extern|;")
DECL_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]* ")
CLOSED_RE = re.compile(r"\(.*\)[ \t]*$")
ENDS_PAREN_RE = re.compile(r"\)[ \t]*$")


def gen_proto(sources, out):
    # The trailing newline is part of the awk's seed string, which yields a
    # blank line between the banner and the first prototype.
    protos = ['/* This file is automatically generated with "make proto". DO NOT EDIT */\n']
    inheader = False

    for src in sources:
        with open(src, "r", errors="replace") as fh:
            for line in fh:
                line = line.rstrip("\n").rstrip("\r")

                if inheader:
                    # Assignment-inside-ternary in the awk: a line ending in
                    # ')' closes the declaration and gets the semicolon.
                    if ENDS_PAREN_RE.search(line):
                        inheader = False
                        protos.append(line + ";")
                    else:
                        protos.append(line)
                    continue

                if FN_RE.match(line):
                    local = line.startswith("FN_LOCAL")
                    text = re.sub(r"^FN_(LOC|GLOB)AL_", "", line)
                    text = re.sub(r",.*$", "", text)
                    for pat, repl in (
                        (r"^BOOL\(", "BOOL "),
                        (r"^CHAR\(", "char "),
                        (r"^INTEGER\(", "int "),
                        (r"^STRING\(", "char *"),
                    ):
                        new = re.sub(pat, repl, text, count=1)
                        if new != text:
                            text = new
                            break
                    protos.append(text + ("(int module_id);" if local else "(void);"))
                    continue

                if SKIP_RE.search(line) or not DECL_RE.match(line):
                    continue

                if CLOSED_RE.search(line):
                    protos.append(line + ";")
                    continue

                if "(" in line:
                    inheader = True
                    protos.append(line)

    _write_if_changed(out, "\n".join(protos) + "\n")


# --------------------------------------------------------------------------
# daemon-parm.awk
# --------------------------------------------------------------------------

PARM_RE = re.compile(r"^(STRING|CHAR|PATH|INTEGER|ENUM|OCTAL|BOOL|BOOLREV|BOOL3)[ \t]")


def gen_daemon_parm(src, out):
    heading = ("/* DO NOT EDIT THIS FILE!  It is auto-generated from a list of "
               "values in %s! */\n\n" % src)
    comment_fmt = "\n/********** %s **********/\n"
    tdstruct = "typedef struct {"

    sect = psect = defines = accessors = prior_ptype = ""
    parms = "\nstatic const struct parm_struct parm_table[] = {"
    values = exps = exp_values = ""

    with open(src, "r") as fh:
        for line in fh:
            line = line.rstrip("\n").rstrip("\r")
            if not line.strip() or line.startswith("#"):
                continue

            if line.startswith("Globals:"):
                if defines != "":
                    sys.exit("The Globals section must come first!")
                defines = tdstruct
                values = "\nstatic const all_vars Defaults = {\n    { /* Globals: */\n"
                exps = exp_values = comment_fmt % "EXP"
                sect, psect = "GLOBAL", ", P_GLOBAL, &Vars.g."
                continue

            if line.startswith("Locals:"):
                if sect == "":
                    sys.exit("The Locals section must come after the Globals!")
                defines += exps + "} global_vars;\n\n" + tdstruct
                values += exp_values + "\n    }, { /* Locals: */\n"
                exps = exp_values = comment_fmt % "EXP"
                sect, psect = "LOCAL", ", P_LOCAL, &Vars.l."
                continue

            if PARM_RE.match(line):
                fields = line.split()
                ptype, name = fields[0], fields[1]
                rest = " ".join(fields[2:])

                if ptype != prior_ptype:
                    comment = comment_fmt % ptype
                    defines += comment
                    values += comment
                    parms += "\n"
                    accessors += "\n"
                    prior_ptype = ptype

                if ptype in ("STRING", "PATH"):
                    atype, vtype = "STRING", "char*"
                elif "BOOL" in ptype:
                    atype = vtype = "BOOL"
                elif ptype == "CHAR":
                    atype, vtype = "CHAR", "char"
                else:
                    atype, vtype = "INTEGER", "int"

                # The name might be var_name|public_name
                pubname = re.sub(r".*\|", "", name).replace("_", " ")
                name = re.sub(r"\|.*", "", name).replace("-", "")

                enum = "enum_" + name if ptype == "ENUM" else "NULL"

                defines += "\t%s %s;\n" % (vtype, name)
                values += "\t%s, /* %s */\n" % (rest, name)
                parms += ' {"%s", P_%s%s%s, %s, 0},\n' % (pubname, ptype, psect, name, enum)
                accessors += "FN_%s_%s(lp_%s, %s)\n" % (sect, atype, name, name)

                if vtype == "char*":
                    exps += "\tBOOL %s_EXP;\n" % name
                    exp_values += "\tFalse, /* %s_EXP */\n" % name
                continue

            sys.exit("Extraneous line:" + line)

    if sect == "" or defines == "":
        sys.exit("Failed to parse the data in " + src)

    defines += exps + "} local_vars;\n\n"
    defines += tdstruct + "\n\tglobal_vars g;\n\tlocal_vars l;\n} all_vars;\n"
    values += exp_values + "\n    }\n};\n\nstatic all_vars Vars;\n"
    parms += "\n {NULL, P_BOOL, P_NONE, NULL, NULL, 0}\n};\n"

    _write_if_changed(out, heading + defines + values + parms + accessors + "\n")


# --------------------------------------------------------------------------
# help-from-md.awk
# --------------------------------------------------------------------------

def gen_help(src, out):
    hfile = os.path.basename(out)
    findcomment = re.compile(r"\[comment\].*" + re.escape(hfile))

    heading = ("/* DO NOT EDIT THIS FILE!  It is auto-generated from the option "
               "list in %s! */" % src)
    prints = ""
    foundcomment = False
    backtick_cnt = 0

    with open(src, "r", errors="replace") as fh:
        for line in fh:
            line = line.rstrip("\n").rstrip("\r")

            if line.startswith("```"):
                backtick_cnt += 1
                continue

            if foundcomment:
                if backtick_cnt > 1:
                    break
                if backtick_cnt == 1:
                    prints += '\n  rprintf(F,"%s\\n");' % line.replace('"', '\\"')
                continue

            if findcomment.search(line):
                foundcomment = True
                backtick_cnt = 0

    if not (foundcomment and backtick_cnt > 1):
        sys.exit("Failed to find %s section in %s" % (hfile, src))

    _write_if_changed(out, heading + "\n" + prints + "\n")


# --------------------------------------------------------------------------
# define-from-md.awk
# --------------------------------------------------------------------------

VALUE_RE = re.compile(r"^    > [^ ]+$")


def gen_define(src, out):
    hfile = os.path.basename(out)
    heading = ("/* DO NOT EDIT THIS FILE!  It is auto-generated from a list of "
               "values in %s! */" % src)

    if "compress" in hfile:
        define, prefix = "#define DEFAULT_DONT_COMPRESS", "*."
    else:
        define, prefix = "#define DEFAULT_CVSIGNORE", ""

    value_list = ""
    with open(src, "r", errors="replace") as fh:
        for line in fh:
            line = line.rstrip("\n").rstrip("\r")

            if VALUE_RE.match(line):
                stripped = line.replace("`", "")
                token = stripped.split()[1]
                if value_list:
                    value_list += " "
                value_list += prefix + token
                continue

            # The awk stops at the end of the first complete block.
            if ".gz " in value_list and "compress" in hfile:
                break
            if "SCCS " in value_list and "cvsignore" in hfile:
                break

            value_list = ""

    if not value_list:
        sys.exit("Failed to find a value list in %s for %s" % (src, hfile))

    _write_if_changed(out, '%s\n\n%s "%s"\n' % (heading, define, value_list))


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("proto", help="generate proto.h")
    p.add_argument("-o", "--output", required=True)
    p.add_argument("sources", nargs="+")

    p = sub.add_parser("daemon-parm", help="generate daemon-parm.h")
    p.add_argument("-o", "--output", required=True)
    p.add_argument("source")

    p = sub.add_parser("help", help="generate help-rsync.h / help-rsyncd.h")
    p.add_argument("-o", "--output", required=True)
    p.add_argument("source")

    p = sub.add_parser("define", help="generate default-*.h")
    p.add_argument("-o", "--output", required=True)
    p.add_argument("source")

    args = ap.parse_args()

    if args.cmd == "proto":
        gen_proto(args.sources, args.output)
    elif args.cmd == "daemon-parm":
        gen_daemon_parm(args.source, args.output)
    elif args.cmd == "help":
        gen_help(args.source, args.output)
    elif args.cmd == "define":
        gen_define(args.source, args.output)


if __name__ == "__main__":
    main()
