name: Lint GitHub Actions workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/*.yml'
      - '.github/actionlint.yaml'
      - '.github/actionlint.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/*.yml'
      - '.github/actionlint.yaml'
      - '.github/actionlint.yml'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: actionlint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: install actionlint
        run: |
          archive=actionlint_1.7.12_linux_amd64.tar.gz
          curl --proto '=https' --tlsv1.2 -fsSLO \
            "https://github.com/rhysd/actionlint/releases/download/v1.7.12/$archive"
          echo "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8  $archive" \
            | sha256sum --check --strict
          tar -xzf "$archive" actionlint
          echo "$PWD" >>"$GITHUB_PATH"
      - name: actionlint --version
        run: actionlint -version
      - name: actionlint .github/workflows/*.yml
        run: actionlint -color
