name: Test rsync on FreeBSD

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/freebsd-build.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/freebsd-build.yml'
  schedule:
    - cron: '42 8 * * 1'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    name: Test rsync on FreeBSD
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: prepare VM host
      timeout-minutes: 10
      run: |
        packages=(qemu-utils qemu-system-x86 ovmf)
        sudo apt-get install -y -q -o Acquire::Retries=3 --no-install-recommends "${packages[@]}" || {
          sudo apt-get update -q
          sudo apt-get install -y -q -o Acquire::Retries=3 --no-install-recommends "${packages[@]}"
        }
    - name: Test in FreeBSD VM
      id: test
      uses: vmactions/freebsd-vm@c46abacb49f09938ca4e1702d15d836285d694cc # v1.5.9
      with:
        cache-after-prepare: true
        prepare: |
          pkg install -y bash autotools m4 devel/xxhash zstd liblz4 python3 archivers/liblz4 git
        run: |
          freebsd-version
          ./configure --with-rrsync \
            -disable-zstd --disable-md2man --disable-xxhash --disable-lz4 --disable-idn \
            --enable-roll-simd --enable-roll-asm --enable-md5-asm
          make
          ./rsync --version
          make check
          ./testsuite/runtests.py --rsync-bin=`pwd`/rsync --use-tcp -j 8
          ./rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
    - name: save artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        retention-days: 45
        name: freebsd-bin
        path: |
          rsync
          rsync-ssl
          rsync.1
          rsync-ssl.1
          rsyncd.conf.5
          rrsync.1
          rrsync
