name: Test rsync on NetBSD

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/netbsd-build.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/netbsd-build.yml'
  schedule:
    - cron: '42 8 * * 1'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    name: Test rsync on NetBSD
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: prepare VM host
      timeout-minutes: 10
      run: |
        packages=(qemu-utils qemu-system-x86 ovmf)
        sudo apt-get install -y -q -o Acquire::Retries=3 --no-install-recommends "${packages[@]}" || {
          sudo apt-get update -q
          sudo apt-get install -y -q -o Acquire::Retries=3 --no-install-recommends "${packages[@]}"
        }
    - name: Test in NetBSD VM
      id: test
      uses: vmactions/netbsd-vm@c8a0d7ddb84619a7a8cc4e652efa7950b3fd9f92 # v1.5.2
      with:
        cache-after-prepare: true
        prepare: |
          PATH=/usr/sbin:$PATH pkg_add autoconf automake python312
          ln -sf /usr/pkg/bin/python3.12 /usr/pkg/bin/python3
        run: |
          uname -a
          ./configure --with-rrsync --disable-zstd --disable-md2man --disable-xxhash --disable-lz4 --disable-idn
          make
          ./rsync --version
          make check
          ./testsuite/runtests.py --rsync-bin=`pwd`/rsync --use-tcp -j 8
          ./rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
    - name: save artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        retention-days: 45
        name: netbsd-bin
        path: |
          rsync
          rsync-ssl
          rsync.1
          rsync-ssl.1
          rsyncd.conf.5
          rrsync.1
          rrsync
